import type { Metadata } from 'next';
import { siteConfig } from '@/lib/site';

/** Route of the generated social card (src/app/opengraph-image.tsx) and its rendered size. */
const OG_IMAGE_PATH = '/opengraph-image';
const OG_IMAGE_SIZE = { width: 1200, height: 630 };

interface GenerateMetadataProps {
  title?: string;
  description?: string;
  path?: string;
  keywords?: string[];
  locale?: 'ja' | 'en';
}

/**
 * Generate metadata for pages in the App Router
 * This provides SEO meta tags support that was previously handled in PageLayout
 */
export function generatePageMetadata({
  title,
  description = siteConfig.description,
  path = '',
  keywords = [],
  locale = 'ja',
}: GenerateMetadataProps = {}): Metadata {
  const localizedSite = locale === 'en'
    ? {
        ...siteConfig,
        personName: siteConfig.personNameEn,
        siteName: `${siteConfig.personNameEn}'s Portfolio`,
        defaultTitle: `${siteConfig.personNameEn} | Portfolio`,
        description: "Koshi Motegi's portfolio featuring research, development experience, and publications.",
        locale: 'en_US',
      }
    : siteConfig;
  const resolvedDescription = description === siteConfig.description && locale === 'en'
    ? localizedSite.description
    : description;
  const fullTitle = title ? `${title} | ${localizedSite.personName}` : localizedSite.defaultTitle;
  const siteUrl = localizedSite.siteUrl;
  const fullUrl = siteUrl ? new URL(path || '/', siteUrl).toString() : undefined;
  const unprefixedPath = path.replace(/^\/(?:ja|en)(?=\/|$)/, '') || '/';
  const counterpartPrefix = locale === 'en' ? '/ja' : '/en';
  const counterpartPath = unprefixedPath === '/'
    ? counterpartPrefix
    : `${counterpartPrefix}${unprefixedPath}`;
  const counterpartUrl = siteUrl ? new URL(counterpartPath, siteUrl).toString() : undefined;
  const localizedPrimaryPaths = new Set([
    '/ja', '/ja/career', '/ja/publications', '/ja/dev-experience',
    '/en', '/en/career', '/en/publications', '/en/dev-experience',
  ]);
  const hasLanguageAlternate = localizedPrimaryPaths.has(path);
  // The card itself is generated by src/app/opengraph-image.tsx. It is wired in here instead of
  // being left to the file convention because every page exports its own `openGraph` object,
  // which replaces the one the root layout resolved - the file-based image would be dropped on
  // all but the root route. Declaring `images` (even as undefined) also keeps Next from falling
  // back to the convention and publishing a http://localhost:3000 card when no site URL is set.
  const socialImages = siteUrl
    ? [
        {
          url: new URL(OG_IMAGE_PATH, siteUrl).toString(),
          width: OG_IMAGE_SIZE.width,
          height: OG_IMAGE_SIZE.height,
          alt: localizedSite.siteName,
        },
      ]
    : undefined;

  return {
    title: fullTitle,
    description: resolvedDescription,
    keywords,
    authors: [{ name: localizedSite.personName }],
    creator: localizedSite.personName,
    publisher: localizedSite.personName,
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        'max-video-preview': -1,
        'max-image-preview': 'large',
        'max-snippet': -1,
      },
    },
    openGraph: {
      type: 'website',
      locale: localizedSite.locale,
      title: fullTitle,
      description: resolvedDescription,
      siteName: localizedSite.siteName,
      images: socialImages,
      ...(fullUrl ? { url: fullUrl } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description: resolvedDescription,
      images: socialImages,
    },
    alternates: fullUrl
      ? {
          canonical: fullUrl,
          ...(hasLanguageAlternate ? {
            languages: {
              ja: locale === 'ja' ? fullUrl : counterpartUrl!,
              en: locale === 'en' ? fullUrl : counterpartUrl!,
            },
          } : {}),
        }
      : undefined,
    // `icons` is deliberately absent: any value here replaces the icons Next collects from the
    // file conventions, which would drop the generated icon.tsx and apple-icon.tsx links from
    // the head. favicon.ico is emitted by Next on its own.
    manifest: '/manifest.webmanifest',
    other: {
      'theme-color': '#ffffff',
      'color-scheme': 'light dark',
    },
  };
}

/**
 * Default metadata for the site
 */
export const defaultMetadata: Metadata = generatePageMetadata({
  path: '/ja',
  keywords: ['茂木光志', 'Koshi Motegi', '自然言語処理', 'NLP', '名古屋大学', '開発経験', '論文'],
});
