import { MetadataRoute } from 'next';
import { siteConfig } from '@/lib/site';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: siteConfig.siteName,
    short_name: siteConfig.personName,
    description: siteConfig.description,
    start_url: '/ja',
    display: 'standalone',
    background_color: '#ffffff',
    theme_color: '#111827',
    // /icon/192 and /icon/512 are the ids generated by src/app/icon.tsx; installing the site to
    // a home screen needs both sizes, and the .ico alone is too small for any launcher.
    icons: [
      {
        src: '/favicon.ico',
        sizes: '48x48',
        type: 'image/x-icon',
      },
      {
        src: '/icon/192',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon/512',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
    ],
  };
}
